### ISSUE TITLE
No database selected error 

### ISSUE THREAD

**Issue by singhPrasan** [airavata-courses/saurabh#3]
![error-db](https://user-images.githubusercontent.com/22266716/29939404-ba3dbc84-8e59-11e7-9b0b-283706e3b6a0.png)

Getting the above error while trying to execute the first db script.

**Comment by singhPrasan** [comment]
Works!

**Comment by singhPrasan** [comment]
![db-error](https://user-images.githubusercontent.com/22266716/29939788-11a4d952-8e5b-11e7-8753-81f807501b8c.png)

The database is getting created but it is empty

**Comment by saurabhagrawal0412** [comment]
Hi @SinghPrasandeep,
Have corrected the SQL script.
Please find the new [authentication-db.sql](https://github.com/airavata-courses/saurabhagrawal0412/blob/master/db_scripts/authentication-db.sql) script.

Thanks

**Comment by saurabhagrawal0412** [comment]
Hi @SinghPrasandeep ,
All the scripts should be working now.
Previously, the scripts were not working because the users and databases (for resource-db and authorization-db) were already created, and these scripts try to create those again.
Now, I have changed the scripts so that they don't try to create database objects if they already exist.

**Comment by singhPrasan** [comment]
@saurabhagrawal0412  all scripts are working after a fresh pull.
