### ISSUE TITLE
Wiki Update for MQs

### ISSUE THREAD

**Issue by jeffreypeter** [airavata-courses/saurabh#8]
Please update your wiki so that I can understand you implementation using RabbitMQs

**Comment by saurabhagrawal0412** [comment]
Updating

**Comment by saurabhagrawal0412** [comment]
@jeffreypeter @sachinkariyattin ,
Have updated the [WIKI](https://github.com/airavata-courses/saurabh/wiki/Assignment-2).
It lists the updated design and the current status.

**Comment by jerrin92** [comment]
Could you add the steps for testing the same? At the moment it says to read the individual README.md, however, I couldn't find any for Assignment2 and the ones in Assignment1 are not valid anymore.

It would be great if you could add a wiki with how to run the system as a whole rather than reading from individual READMEs.

**Comment by saurabhagrawal0412** [comment]
Added the design and steps to test in the [Wiki](https://github.com/airavata-courses/saurabh/wiki/Assignment-2)
